version: '3'

volumes:
  pg_data:
  static:
  users_media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: greenvibe/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - users_media:/app/users_media
  frontend:
    env_file: .env
    image: greenvibe/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: greenvibe/kittygram_gateway
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles
      - users_media:/app/users_media
